### ISSUE TITLE
Saves the image as transparent. 

### ISSUE THREAD

**Issue by tukideniz** [tukideniz/Paint-App#1]
![paint](https://user-images.githubusercontent.com/75500832/129228259-f51b6113-026d-4ff3-9623-57f090084d7c.jpg)
SaveFileDialog class doesn't work properly. It only saves the drawn shapes but also shows the deleted areas as drawn by user. 
`private void btn_save_Click(object sender, EventArgs e)
        {
            SaveFileDialog save = new SaveFileDialog();
            save.Filter = "JPG files (*.jpg)|*.jpg|All files (*.*)|*.*";          
            if (save.ShowDialog()==DialogResult.OK)
            {  
                  img.Image.Save(save.FileName);
            }
      
        }`

**Comment by erdemuysal** [comment]
I think code block should be presented as follows.

Also, the problem you mentioned may be due to the fact that you are filling the deleted parts as white.

```c#
private void btn_save_Click(object sender, EventArgs e)
{
    SaveFileDialog save = new SaveFileDialog();
    save.Filter = "JPG files (.jpg)|.jpg|All files (.)|.";
    if (save.ShowDialog()==DialogResult.OK)
    {
        img.Image.Save(save.FileName);
    }
}
```

when you write markdown codeblocks should be arranged as follows
````
```c#
private void btn_save_Click(object sender, EventArgs e)
{
    SaveFileDialog save = new SaveFileDialog();
    save.Filter = "JPG files (.jpg)|.jpg|All files (.)|.";
    if (save.ShowDialog()==DialogResult.OK)
    {
        img.Image.Save(save.FileName);
    }
}
```
````
